language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

services: mysql

env:
  - DJANGO="django==1.7.11" DB="mysql"
  - DJANGO="django==1.8.18" DB="mysql"
  - DJANGO="django==1.9.13" DB="mysql"
  - DJANGO="django==1.10.7" DB="mysql"
  - DJANGO="django==1.11.3" DB="mysql"

install:
  - pip install $DJANGO
  - pip install celery==4.1.0
  - pip install coveralls
  - pip install mysqlclient

before_script:
  - mysql -e 'create database testdb;'

script:
  - coverage run --source=djcelery_transactions runtests.py

after_success:
  coveralls

notifications:
  email:
    recipients:
      - haos616@gmail.com
    on_success: change
    on_failure: change
